name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Load Lambda Toolkit
      run: go get -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip

    - name: Build Lambda Function
      run: go build -o main lambda/main.go
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
       name: checkssl-lambda
       path: main

    
